import { chromium } from 'file:///C:/Users/anand/.agents/skills/gstack/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
const mode=process.argv[2]||'hero';
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:mode==='mobile'?390:mode==='front'?1600:1440,height:mode==='mobile'?844:mode==='front'?1200:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://127.0.0.1:5173/'+(mode==='front'?'?lab=1&view=front':''),{waitUntil:'domcontentloaded',timeout:60000});
await page.waitForFunction(()=>window.__DUALSENSE__||!document.querySelector('#render-error').hidden,{timeout:60000});
await page.evaluate(()=>document.fonts.ready);
if(mode==='inside')await page.evaluate(()=>scrollTo(0,document.querySelector('#inside').offsetTop));
if(mode==='texture')await page.evaluate(()=>scrollTo(0,document.querySelector('#texture').offsetTop));
await page.waitForTimeout(1500);
await page.screenshot({path:`artifacts/${mode}-001.png`});
console.log(JSON.stringify({mode,errors,info:await page.evaluate(()=>window.__DUALSENSE__?.getInfo()),title:await page.title()},null,2));
await browser.close();
